language: node_js
node_js:
- '4.1'
- '4.0'
before_deploy: npm install -g babel-cli
deploy:
  tags: true
  branch: master
  provider: npm
  email: eknuth@gmail.com
  api_key:
    secure: K3QxLUsDw4nQKv3wicOIKaRNQXQsq/3i07PRYWLRTBBJr0uU84uGAoJ/wZEoqm4EgEmfDkQkrwrSjlUZBHwNGCoHHpKWgwN+LUYwL8R/DMJtznI6dJzFi3mCldL05ZK4O+szzsGV7vtYPOB9wwJMn4idyXPn4k+Nc9FeFYS1QQqV8y+QA5dOGjeTpyn7kJZhfgnnndD7qHv8rPN7k8sAhzfPiT6pEt38FWG9vfyN5FnRS81uil80pdgFCL0iLpdj7Q72//FNWQB+bYIt7KHzxEP+RKhZiJSK3qzcJufAaxM4bqGwp3UCGzSITjDAqA7DI4yQbxWWJGxlCOnH1kjVmOxvCmqoRXONRad+fAlgH0qgPQZg6m+Of0KpxjNFiujpaJxx58wTl2V/mKvOsSGygJOH8tDlU/m0DYbzDsXy3lATRFY2bWk2PRIJoExS+7oF6087g1eQ/KbRYueb1CXUkrLE3j0++PVhqb+GM4w8lNJSpb4VIzygW7iISbv7YiRnHkiWNCdv87KVBGA2LJbpbzVehp2vnAd3hEgwzJ1/4NtOkSU3vw1Lbt4uC1nKVnAzWJj5iF+T6J1t1jtwBR2Dy1h37aigmir8p1CCO82izG0W4+1A8u6dm7aVjkDysHTgRzrrga0Tc8Xa/Cukn31vEvKCJJsGxHtZlubIMxPB4O8=
after_failure: cat /home/travis/build/eknuth/react-honeycomb-loading-spinner/npm-debug.log
